FROM node:20-bookworm-slim
RUN apt-get update -y && apt-get install -y openssl
RUN npm install -g pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN pnpm config set store-dir /app/.pnpm-store
RUN pnpm install
COPY . .
EXPOSE 4000
CMD ["pnpm", "run", "start:dev"]
